---
version: '3.3'

#networks:
#    host:
#        name: host
#        external: true
#        driver: host

services:
    ros-master:
        image: ros:melodic-ros-core
        command: stdbuf -o L roscore
        ports:
            - 11311:11311
        network_mode: "host"
    ros1:
        build: ros1

        command: bash -c "chmod +777 /home/dev_ws/src/era_5g_action_client_ros1/scripts/era_5g_action_client_script.py && chmod +777 /home/dev_ws/src/era_5g_action_server_ros1/scripts/era_5g_action_server_script.py && source /opt/ros/melodic/setup.bash && cd /home/dev_ws/ && catkin_make && source devel/setup.bash &&  rosrun rospy_tutorials talker"

        environment:
            - "ROS_MASTER_URI=http://127.0.0.1:11311"
        network_mode: "host"
        depends_on:
            - ros-master
