version: '3.4'

services:
  redisinterface:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=7091
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=ros
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - REDIS_PORT=${REDIS_PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - CENTRAL_API_HOSTNAME=central.api
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - Middleware__Organization=5G-ERA-DEV
      - Middleware__InstanceName=MiddlewareBB
      - Middleware__InstanceType=Edge
    ports:
      - "5091:80"
      - "7091:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      #- ~/.aspnet/https:/https:ro
  orchestrator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=7026
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=ros
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx 
      - REDIS_INTERFACE_API_SERVICE_HOST=redisinterface.api
      - AWS_IMAGE_REGISTRY=${AWS_IMAGE_REGISTRY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - REDIS_PORT=${REDIS_PORT}
      - CENTRAL_API_HOSTNAME=central.api
      - Middleware__Organization=5G-ERA-DEV
      - Middleware__InstanceName=MiddlewareBB
      - Middleware__InstanceType=Edge
      - Middleware__Address=localhost:5047

    ports:
      - "5036:80"
      - "7036:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      #- ~/.aspnet/https:/https:ro

  taskplanner:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - REDIS_INTERFACE_API_SERVICE_HOST=redisinterface.api
      - RESOURCE_PLANNER_API_SERVICE_HOST=resourceplanner.api
      - ORCHESTRATOR_API_SERVICE_HOST=orchestrator.api
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}      
      - CENTRAL_API_HOSTNAME=central.api
      - Middleware__Organization=5G-ERA-DEV
      - Middleware__InstanceName=MiddlewareBB
      - Middleware__InstanceType=Edge
    ports:
      - "5143:80"
      - "7094:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  resourceplanner:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - REDIS_INTERFACE_API_SERVICE_HOST=redisinterface.api
      - ORCHESTRATOR_API_SERVICE_HOST=orchestrator.api
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - CENTRAL_API_HOSTNAME=central.api
      - Middleware__Organization=5G-ERA-DEV
      - Middleware__InstanceName=MiddlewareBB
      - Middleware__InstanceType=Edge
    ports:
      - "5263:80"
      - "7263:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ocelotgateway:

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - REDIS_INTERFACE_API_SERVICE_HOST=redisinterface.api
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - REDIS_PORT=${REDIS_PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - Middleware__Organization=5G-ERA-DEV
      - Middleware__InstanceName=MiddlewareBB
      - Middleware__InstanceType=Edge
    ports:
      - "5047:80"
      - "7047:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  centralapi:

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "5058:80"
      - "7058:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
