version: '3.4'

services:
  redisinterface:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80      
      - ASPNETCORE_HTTPS_PORT=7091
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=ros
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "5091:80"
      - "7091:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      #- ~/.aspnet/https:/https:ro
  orchestrator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=7026
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=ros
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx 
      - REDIS_INTERFACE_ADDRESS=http://redisinterface.api
      - AWS_IMAGE_REGISTRY=${AWS_IMAGE_REGISTRY}
    ports:
      - "5036:80"
      - "7036:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      #- ~/.aspnet/https:/https:ro

  taskplanner:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - REDIS_INTERFACE_ADDRESS=http://redisinterface.api
      - RESOURCE_PLANNER_ADDRESS=http://resourceplanner.api
    ports:
      - "5143:80"
      - "7094:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  resourceplanner:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - REDIS_INTERFACE_ADDRESS=http://redisinterface.api
    ports:
      - "5263:80"
      - "7263:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ocelotgateway:

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "5047:80"
      - "7047:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
