version: '3.4'

services:
  redisinterface:
    container_name: redisinterface.api
    image: ${DOCKER_REGISTRY-}redisinterface
    build:
      context: .
      dockerfile: src/RedisInterface/Dockerfile
    networks: 
      - middleware

  orchestrator:
    container_name: orchestrator.api
    image: ${DOCKER_REGISTRY-}orchestrator
    build:
      context: .
      dockerfile: src/Orchestrator/Dockerfile
    networks: 
      - middleware


  taskplanner:
    container_name: taskplanner.api
    image: ${DOCKER_REGISTRY-}taskplanner
    build:
      context: .
      dockerfile: src/TaskPlanner/Dockerfile
    networks: 
      - middleware


  resourceplanner:
    container_name: resourceplanner.api
    image: ${DOCKER_REGISTRY-}resourceplanner
    build:
      context: .
      dockerfile: src/ResourcePlanner/Dockerfile
    networks: 
      - middleware


  ocelotgateway:
    container_name: ocelotgateway.api
    image: ${DOCKER_REGISTRY-}ocelotgateway
    build:
      context: .
      dockerfile: src/OcelotGateway/Dockerfile
    networks: 
      - middleware


networks:
     middleware:
       driver: bridge
       name: middleware_network

