apiVersion: v1
kind: Service
metadata:
  name: orchestrator-api
spec:
  type: LoadBalancer
  selector:
    name: orchestrator-api
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 433
    targetPort: 433
    name: https