apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orchestrator
subjects:
  - kind: ServiceAccount
    # Reference to ServiceAccount kind's `metadata.name`
    name: orchestrator
    # Reference to ServiceAccount kind's `metadata.namespace`
    namespace: middleware
roleRef:
  kind: ClusterRole
  name: orchestrator
  apiGroup: rbac.authorization.k8s.io