apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-api
spec:
  selector:
    matchLabels:
      name: central-api
  template:
    metadata:
      labels:
        name: central-api
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      imagePullSecrets:
        - name: awsecr-cred
      containers:
        - name: central-api
          image: 394603622351.dkr.ecr.eu-west-1.amazonaws.com/central-api:v0.3-rc1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.5"
              memory: "200Mi"
            requests:
              cpu: "0.2"
              memory: "100Mi"
