apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-api
spec:
  selector:
    matchLabels:
      app: central-api
  template:
    metadata:
      labels:
        app: central-api
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      imagePullSecrets:
        - name: awsecr-cred
      containers:
        - name: central-api
          image: ghcr.io/5g-era/central-api:edge
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.5"
              memory: "200Mi"
            requests:
              cpu: "0.2"
              memory: "100Mi"
