apiVersion: v1
kind: Service
metadata:
  name: orchestrator-api
spec:
  type: ClusterIP
  selector:
    name: orchestrator-api
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 433
    targetPort: 433
    name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-api
spec:
  selector:
    matchLabels:
      name: orchestrator-api
  template:
    metadata:
      labels:
        name: orchestrator-api
    spec:
      serviceAccountName: orchestrator
      automountServiceAccountToken: true
      nodeSelector:
        kubernetes.io/os: linux
      containers:        
      - name: orchestrator-api
        image: 394603622351.dkr.ecr.eu-west-1.amazonaws.com/orchestrator-api:v0.1.4
        imagePullPolicy: Always
        resources: {}
        env:
        - name: AWS_IMAGE_REGISTRY
          value: 394603622351.dkr.ecr.eu-west-1.amazonaws.com # to be replaced with real value
        - name: REDIS_INTERFACE_ADDRESS
          value: http://redis-interface-api # to be replaced with real value
