apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      name: gateway
  template:
    metadata:
      labels:
        name: gateway
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: gateway
          image: ghcr.io/5g-era/gateway:latest
          imagePullPolicy: IfNotPresent
          resources: {}
