apiVersion: v1
kind: Service
metadata:
  name: redis-master
spec:
  type: NodePort
  ports:
  - port: 6380
    targetPort: 6379
    nodePort: 31002
    name: redis
  selector:
    app: redis
    statefulset.kubernetes.io/pod-name: redis-0