apiVersion: apps/v1
kind: Deployment
metadata:
  name: teleoperation
spec:
  selector:
    matchLabels:
      app: teleoperation
  replicas: 1
  template:
    metadata:
      labels:
        app: teleoperation
    spec:
      containers:
        - name: teleoperation
          resources: {}
          image: alenrobots/5gera_teleop
