apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-interface-api
spec:
  selector:
    matchLabels:
      name: redis-interface-api
  template:
    metadata:
      labels:
        name: redis-interface-api
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:        
      - name: redis-interface-api
        image: 394603622351.dkr.ecr.eu-west-1.amazonaws.com/redis-interface-api:latest
        imagePullPolicy: Always
        resources: {}
        env:
        - name: REDIS_HOSTNAME
          value: $(REDIS_HOSTNAME) # to be changed with real value
        - name: REDIS_PORT
          value: $(REDIS_PORT) # to be changed with real value