apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-interface-api
spec:
  selector:
    matchLabels:
      name: redis-interface-api
  template:
    metadata:
      labels:
        name: redis-interface-api
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: redis-interface-api
          image: ghcr.io/5g-era/redis-interface-api:latest
          imagePullPolicy: Always
          resources: {}
          env:
            - name: REDIS_HOSTNAME
              value: ec2-18-133-117-215.eu-west-2.compute.amazonaws.com # to be changed with real value
            - name: REDIS_PORT
              value: "6309" # to be changed with real value
