name: Orchestrator docker build on tag

on:
  push:
    tags:  [ v* ]

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Build image
      env:
        IMAGE_REPOSITORY: ${{ secrets.ORCHESTRATOR_REPO_NAME }}
      run: docker build -f ./src/Orchestrator/Dockerfile ./src --tag $IMAGE_REPOSITORY --label "runnumber=${GITHUB_RUN_ID}"
    
    - name: Log in to registry
      # This is where you will update the personal access token to GITHUB_TOKEN
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Push image
      env:
        IMAGE_REPOSITORY: ${{ secrets.ORCHESTRATOR_REPO_NAME }}
        IMAGE_TAG: ${{ steps.get_version.outputs.VERSION }}
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_REPOSITORY

        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')          
        docker tag $IMAGE_REPOSITORY $IMAGE_ID:$IMAGE_TAG
        docker push $IMAGE_ID:$IMAGE_TAG
        docker tag $IMAGE_ID:$IMAGE_TAG $IMAGE_ID:latest
        docker push $IMAGE_ID:latest
  
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_REPOSITORY: ${{ secrets.ORCHESTRATOR_REPO_NAME }}
        AWS_KEY_ID: ${{ secrets.AWS_APP_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_APP_SECRET_KEY }}
        IMAGE_TAG: ${{ steps.get_version.outputs.VERSION }}
      run: |
        # Build a docker container and push it to ECR 
        docker build -f ./src/Orchestrator/Dockerfile -t $ECR_REGISTRY/$IMAGE_REPOSITORY:$IMAGE_TAG \
        -t $ECR_REGISTRY/$IMAGE_REPOSITORY:latest \
         --build-arg AWS_KEY_ID=$AWS_KEY_ID --build-arg AWS_SECRET_KEY=$AWS_SECRET_KEY ./src
        echo "Pushing image with tag $IMAGE_TAG to ECR..."
        docker push $ECR_REGISTRY/$IMAGE_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$IMAGE_REPOSITORY:$IMAGE_TAG"
        echo "Pushing image with tag latest to ECR..."
        docker push $ECR_REGISTRY/$IMAGE_REPOSITORY:latest
        echo "::set-output name=image::$ECR_REGISTRY/$IMAGE_REPOSITORY:latest"
