name: Resource Planner docker build on tag

on:
  push:
    tags:  [ v* ]

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3   
  
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    
    - name: Build image
      env:
        IMAGE_REPOSITORY: ${{ secrets.RESOURCE_PLANNER_REPO_NAME }}
      run: docker build -f ./src/ResourcePlanner/Dockerfile ./src --tag $IMAGE_REPOSITORY --label "runnumber=${GITHUB_RUN_ID}"
    
    - name: Log in to registry
      # This is where you will update the personal access token to GITHUB_TOKEN
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Push image
      env:
        IMAGE_REPOSITORY: ${{ secrets.RESOURCE_PLANNER_REPO_NAME }}
        IMAGE_TAG: ${{ steps.get_version.outputs.VERSION }}
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_REPOSITORY

        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')          
        docker tag $IMAGE_REPOSITORY $IMAGE_ID:$IMAGE_TAG
        docker push $IMAGE_ID:$IMAGE_TAG
        if [[ ${{ steps.get_version.outputs.VERSION }} != *rc* && ${{ steps.get_version.outputs.VERSION }} != *beta*]]; then
            docker tag $IMAGE_ID:$IMAGE_TAG $IMAGE_ID:latest
            docker push $IMAGE_ID:latest
        fi
