name: Resource Planner docker build

on:
  workflow_dispatch:    
  schedule:
    - cron: 0 3 * * 1-5

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build image
      env:
        IMAGE_REPOSITORY: ${{ secrets.RESOURCE_PLANNER_REPO_NAME }}
      run: docker build -f ./src/ResourcePlanner/Dockerfile ./src --tag $IMAGE_REPOSITORY --label "runnumber=${GITHUB_RUN_ID}"
    
    - name: Log in to registry
      # This is where you will update the personal access token to GITHUB_TOKEN
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Push image
      env:
        IMAGE_REPOSITORY: ${{ secrets.RESOURCE_PLANNER_REPO_NAME }}
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_REPOSITORY

        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')          
        # Use Docker `edge` tag convention
        VERSION=edge
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag $IMAGE_REPOSITORY $IMAGE_ID:edge
        docker push $IMAGE_ID:edge
